function myCreateFigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Dec-2020 18:36:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','A_x');
set(plot1(2),'DisplayName','A_y');
set(plot1(3),'DisplayName','A_z');

% Create ylabel
ylabel('Acceleration (m/s^2)');

% Create xlabel
xlabel('Time (s)');

% Create title
title('Acceleration Data from Mobile Sensor');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

